config/routes.rb
CiteCollections::Application.routes.draw do
  
  get "cite/index"
  resources :versions, :constraints => {:id => /urn:cite:\w+:\w+\.*\w*\.*\w*-*\w*/}, only: [:index, :show, :edit, :update] do
    collection do
      get 'search'
    end
  end

  resources :works, :constraints => {:id => /urn:cite:\w+:\w+\.*\w*\.*\w*-*\w*/}, only: [:index, :show, :edit, :update] do
    collection do
        get 'search'
      end
    end

  resources :textgroups, :constraints => {:id => /urn:cite:\w+:\w+\.*\w*\.*\w*-*\w*/}, only: [:index, :show, :edit, :update] do
    collection do
      get 'search'
    end
  end

  resources :authors, :constraints => {:id => /urn:cite:\w+:\w+\.*\w*\.*\w*-*\w*/}, only: [:index, :show, :edit, :update] do
    collection do
      get 'search'
    end
  end

  get 'forms' => 'forms#index'
  post 'forms/search' => 'forms#search'
  post 'forms/reserve' => 'forms#reserve'
  post 'forms/create' => 'forms#create'
  post 'forms/mods' => 'forms#mods'
  post 'forms/mads' => 'forms#mads'

  namespace :api do
    resources :authors, :works, :textgroups, :versions, :constraints => {:id => /urn:cite:\w+:\w+\.*\w*\.*\w*-*\w*/}, only: [:index, :show] do
      collection do
        get 'count'
        get 'first'
        get 'last'
        get 'search'
        get 'redirect'
      end
      member do
        get 'previous'
        get 'next'
        get 'prevnext'
      end
    end
    resources :forms, only: [:show] do
      get 'reserve', on: :collection
    end
  end

    

   root 'cite#index'

  

end

app/models/version.rb
class Version < ActiveRecord::Base
  belongs_to :work
  
  def self.latest_urn
    latest_urn = Version.last['urn']
  end

  def self.generate_urn
    last_urn = Version.latest_urn
    unless last_urn
      new_urn = "urn:cite:perseus:catver.1.1"
    else
      urn_parts = last_urn.split('.')
      inc_urn = urn_parts[1].to_i + 1
      new_urn = "urn:cite:perseus:catver.#{inc_urn}.1"
    end
  end

  def self.cts_num_incr(existing_vers, v_cts_no_num)
    num = nil
    existing_vers.each do |line|
      curr_urn = line[:version][/#{v_cts_no_num}\d+/]
      urn_num = curr_urn[/\d+$/].to_i
      num = urn_num + 1
    end
    return num
  end

  def self.find_by_cts(id)
    found_ids = Version.find(:all, :conditions => ["version rlike ?", id])
  end

  def self.update_row(cts, vers_label, vers_desc, editor, has_mods=false, status="")
    vers = Version.find_by_cts(cts)[0]
    v_hash = {}            
    v_hash[:label_eng] = vers_label if vers.label_eng != vers_label
    v_hash[:desc_eng] = vers_desc if vers.desc_eng != vers_desc
    v_hash[:has_mods] = "true" if has_mods
    v_hash[:urn_status] = status if status != ""
    unless v_hash.empty?
      v_hash[:edited_by] = editor
      Version.update(vers.id, v_hash)
    end
  end

  def self.is_match(
    #0urn, 1version, 2label_eng, 3desc_eng, 4type, 5has_mods, 6urn_status, 
    #7redirect_to, 8member_of, 9created_by, 10edited_by
    urn_match = v[0].sub(/\d+/,'')
    found = Version.where(:conditions => 
      { "version rlike ?" =>  urn_match, 
        "label_eng" => v[2],
        "desc_eng" => v[3],
        "ver_type" => v[4],
        "has_mods" => v[5],
        "urn_status" => v[6],
        "member_of" => v[8]
      })
    return found
  end

  def self.add_cite_row(v)
    #0urn, 1version, 2label_eng, 3desc_eng, 4type, 5has_mods, 6urn_status, 
    #7redirect_to, 8member_of, 9created_by, 10edited_by
    vers = Version.new do |vr|
      vr.urn = v[0]
      vr.version = v[1]
      vr.label_eng = v[2]
      vr.desc_eng = v[3] 
      vr.ver_type = v[4] 
      vr.has_mods = v[5]
      vr.urn_status = v[6] 
      vr.redirect_to = v[7]
      vr.member_of = v[8]
      vr.created_by = v[9]
      vr.edited_by = v[10]
      vr.source_urn = v[11]
    end
    vers.save
  end

  def self.lookup(params)
    type = params[:field_type]
    search = params[:search]
    valid_cols = ['urn', 'version', 'label_eng', 'desc_eng', 'type', 'has_mods', 'urn_status', 'redirect_to', 'member_of', 'created_by', 'edited_by']
    if valid_cols.include?(type)
      result = Version.all(:conditions => ["#{type} rlike ?", search])
    else
      result = nil
    end
  end

  def prev
    unless self.id == 1
      prev = Version.find(self.id - 1)
    else
      prev = nil
    end
    return prev
  end

  def next
    unless self.id == Version.last.id
      nxt = Version.find(self.id + 1)
    else
      nxt = nil
    end
    return nxt
  end

  def prevnext
    prev = self.prev
    nxt = self.next
    return prev, nxt
  end

end

app/controllers/api/versions_controller.rb
module Api
  class VersionsController < ApplicationController
    respond_to :json, :xml
    before_action :set_version, only: [:show, :previous, :next, :prevnext]
    before_filter :default_format_xml

    def default_format_xml
      request.format = "xml" unless params[:format]
    end
    
    def index
      @versions = Version.all
      respond_with(@versions, except: :id)
    end

    def show
      respond_with(@version, except: :id)
    end

    def count     
      c = Version.count
      @count = {:collection_size => c}
      respond_with(@count)
    end

    def first
      @first = Version.first
      respond_with(@first, except: :id)
    end

    def last
      @last = Version.last
      respond_with(@last, except: :id)
    end

    def previous
      @prev = @version.prev
      respond_with(@prev, except: :id)
    end

    def next
      @next = @version.next
      respond_with(@next, except: :id)
    end

    def prevnext
      @prev, @next = @version.prevnext
      @both = {:previous => @prev, :next => @next}
      respond_with(@both, except: :id)
    end

    def search
      received = params.permit(:urn, :version, :label_eng, :desc_eng, :type, :has_mods, :urn_status, :redirect_to, :member_of, :created_by, :edited_by, :source_urn)
      #this allows for a bit of fuzzy searching, could input "tlg0012" and get back all works for it     
      query = []
      received.each  {|k, v| query << "#{k} rlike #{ActiveRecord::Base.sanitize("#{v}")}"}
      @response = Version.where(query.join(" AND "))
      respond_with(@response, except: :id)
    end

    def redirect
      # hack to handle records who have a source urn but have not been 
      # officially redirected yet
      @redirected = Version.where(:source_urn => params[:version])
      if @redirected.length == 0
        @response = Version.where(:version => params[:version])
        if (@response.length == 1) 
          if @response[0][:redirect_to] =~ /^urn:cite/
            @redirected = Version.where(:urn => @response[0][:redirect_to])
          elsif @response[0][:redirect_to] && @response[0][:redirect_to] =~ /^urn:cts/
            @redirected = Version.where(:version => @response[0][:redirect_to])
          else
            @redirected = [@response[0]]
          end
        end
      end
      #TODO this should resppond with a 404 if none found
      # and should responds with a 500? if > 1 found
      # and ideally would only ever return just the urn and not an array
      respond_with(@redirected, only: :version)
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_version
          @version = Version.find_by_urn(params[:id])
      end
    end
end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
  before_filter :authenticate, except: [:show, :index, :search]
  before_action :set_version, only: [:show, :edit, :update, :destroy]

  # GET /versions
  # GET /versions.json
  def index
    session[:search_results] = request.url
    if request.url =~ /json/
      @versions = Version.where(urn_status: ["published", "reserved"])
    else
      @versions = Version.paginate(page: params[:page], per_page: 200)
      respond_to do |format|
        format.html
        format.js
      end
    end
  end

  # GET /versions/1
  # GET /versions/1.json
  def show
  end

  # GET /versions/new
  def new
    @version = Version.new
  end

  # GET /versions/1/edit
  def edit
  end

  # POST /versions
  # POST /versions.json
  def create
    @version = Version.new(version_params)

    respond_to do |format|
      if @version.save
        format.html { redirect_to @version, notice: 'Version was successfully created.' }
        format.json { render action: 'show', status: :created, location: @version }
      else
        format.html { render action: 'new' }
        format.json { render json: @version.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /versions/1
  # PATCH/PUT /versions/1.json
  def update
    respond_to do |format|
      if @version.update(version_params)
        format.html { redirect_to version_path(@version.urn), notice: 'Version was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @version.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /versions/1
  # DELETE /versions/1.json
  def destroy
    @version.destroy
    respond_to do |format|
      format.html { redirect_to versions_url }
      format.json { head :no_content }
    end
  end

  def search
    session[:search_results] = request.url
    @versions = Version.lookup(params)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_version
      @version = Version.find_by_urn(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def version_params
      params.require(:version).permit(:urn, :version, :label_eng, :desc_eng, :ver_type, :has_mods, :urn_status, :redirect_to, :member_of, :created_by, :edited_by, :source_urn)
    end
end

app/helpers/versions_helper.rb
module VersionsHelper
end

app/views/versions/_form.html.erb
<%= form_for @version, :url => version_path do |f| %>
  <% if @version.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@version.errors.count, "error") %> prohibited this version from being saved:</h2>

      <ul>
      <% @version.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :urn %><br>
    <%= f.text_field :urn %>
  </div>
  <div class="field">
    <%= f.label :version %><br>
    <%= f.text_field :version %>
  </div>
  <div class="field">
    <%= f.label :label_eng %><br>
    <%= f.text_area :label_eng %>
  </div>
  <div class="field">
    <%= f.label :desc_eng %><br>
    <%= f.text_area :desc_eng %>
  </div>
  <div class="field">
    <%= f.label :ver_type %><br>
    <%= f.text_field :ver_type %>
  </div>
  <div class="field">
    <%= f.label :has_mods %><br>
    <%= f.text_field :has_mods %>
  </div>
  <div class="field">
    <%= f.label :urn_status %><br>
    <%= f.text_field :urn_status %>
  </div>
  <div class="field">
    <%= f.label :redirect_to %><br>
    <%= f.text_field :redirect_to %>
  </div>
  <div class="field">
    <%= f.label :member_of %><br>
    <%= f.text_field :member_of %>
  </div>
  <div class="field">
    <%= f.label :created_by %><br>
    <%= f.text_field :created_by %>
  </div>
  <div class="field">
    <%= f.label :edited_by %><br>
    <%= f.text_field :edited_by %>
  </div>
  <div class="field">
    <%= f.label :source_urn %><br>
    <%= f.text_field :source_urn %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/versions/_version.html.erb
  <tr>
    <td><%= version.urn %></td>
    <td><%= version.version %></td>
    <td><%= version.label_eng %></td>
    <td><%= version.desc_eng %></td>
    <td><%= version.ver_type %></td>
    <td><%= version.has_mods %></td>
    <td><%= version.urn_status %></td>
    <td><%= version.redirect_to %></td>
    <td><%= version.member_of %></td>
    <td><%= version.created_by %></td>
    <td><%= version.edited_by %></td>
    <td><%= version.source_urn %></td>
    <td><%= link_to 'Show', version_path(version.urn) %></td>
    <td><%= link_to 'Edit', edit_version_path(version.urn) %></td>
  </tr>

app/views/versions/edit.html.erb
<h1>Editing version</h1>

<%= render 'form' %>

<%= link_to 'Show', @version.urn %> |
<%= link_to 'Back', request.referer %>

app/views/versions/index.html.erb
<h1>Listing versions</h1>

<br>
<%= link_to "Return to main page", root_path %>
<br>

<div class="index_table">
  <table>
    <thead>
      <tr>
        <th>Urn</th>
        <th>Version</th>
        <th>Label eng</th>
        <th>Desc eng</th>
        <th>Type</th>
        <th>Has mods</th>
        <th>Urn status</th>
        <th>Redirect to</th>
        <th>Member of</th>
        <th>Created by</th>
        <th>Edited by</th>
        <th></th>
        <th></th>
      </tr>
    </thead>      
    <tbody id="vers_table">
      <%= render @versions %>
    </tbody>
  </table>
</div>

  <div id="infinite-scrolling">
    <%= will_paginate %>
  </div>

app/views/versions/index.js.erb
$('#vers_table').append('<%= j render @versions %>');
<% if @versions.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @versions %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>

app/views/versions/new.html.erb
<h1>New version</h1>

<%= render 'form' %>

<%= link_to 'Back', versions_path %>

app/views/versions/search.html.erb
<% unless @versions == nil || @versions.empty? %>
  <h1>Search Results</h1>

  <table>
    <thead>
      <tr>
        <th>Urn</th>
        <th>Version</th>
        <th>Label eng</th>
        <th>Desc eng</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @versions.each do |version| %>
        <tr>
          <td><%= version.urn %></td>
          <td><%= version.version %></td>
          <td><%= version.label_eng %></td>
          <td><%= version.desc_eng %></td>
          <td><%= link_to 'Show', version_path(version.urn) %></td>
          <td><%= link_to 'Edit', edit_version_path(version.urn) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h1>No results</h1>
  
<% end %>
<br>
<%= link_to "Return to main page", root_path %>

app/views/versions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Urn:</strong>
  <%= @version.urn %>
</p>

<p>
  <strong>Version:</strong>
  <%= @version.version %>
</p>

<p>
  <strong>Label eng:</strong>
  <%= @version.label_eng %>
</p>

<p>
  <strong>Desc eng:</strong>
  <%= @version.desc_eng %>
</p>

<p>
  <strong>Type:</strong>
  <%= @version.ver_type %>
</p>

<p>
  <strong>Has mods:</strong>
  <%= @version.has_mods %>
</p>

<p>
  <strong>Urn status:</strong>
  <%= @version.urn_status %>
</p>

<p>
  <strong>Redirect to:</strong>
  <%= @version.redirect_to %>
</p>

<p>
  <strong>Member of:</strong>
  <%= @version.member_of %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @version.created_by %>
</p>

<p>
  <strong>Edited by:</strong>
  <%= @version.edited_by %>
</p>

<p>
  <strong>Source URN:</strong>
  <%= @version.source_urn %>
</p>

<%= link_to 'Edit', edit_version_path(@version.urn) %> |
<% if request.referer =~ /edit/%>
  <%= link_to 'Back', session[:search_results] %>
<% else %>
  <%= link_to 'Back', request.referer %>
<% end %> |
<%= link_to "Return to main page", root_path %>