config/routes.rb
CiteCollections::Application.routes.draw do
  
  get "cite/index"
  resources :versions, :constraints => {:id => /urn:cite:\w+:\w+\.*\w*\.*\w*-*\w*/}, only: [:index, :show, :edit, :update] do
    collection do
      get 'search'
    end
  end

  resources :works, :constraints => {:id => /urn:cite:\w+:\w+\.*\w*\.*\w*-*\w*/}, only: [:index, :show, :edit, :update] do
    collection do
        get 'search'
      end
    end

  resources :textgroups, :constraints => {:id => /urn:cite:\w+:\w+\.*\w*\.*\w*-*\w*/}, only: [:index, :show, :edit, :update] do
    collection do
      get 'search'
    end
  end

  resources :authors, :constraints => {:id => /urn:cite:\w+:\w+\.*\w*\.*\w*-*\w*/}, only: [:index, :show, :edit, :update] do
    collection do
      get 'search'
    end
  end

  get 'forms' => 'forms#index'
  post 'forms/search' => 'forms#search'
  post 'forms/reserve' => 'forms#reserve'
  post 'forms/create' => 'forms#create'
  post 'forms/mods' => 'forms#mods'
  post 'forms/mads' => 'forms#mads'

  namespace :api do
    resources :authors, :works, :textgroups, :versions, :constraints => {:id => /urn:cite:\w+:\w+\.*\w*\.*\w*-*\w*/}, only: [:index, :show] do
      collection do
        get 'count'
        get 'first'
        get 'last'
        get 'search'
        get 'redirect'
      end
      member do
        get 'previous'
        get 'next'
        get 'prevnext'
      end
    end
    resources :forms, only: [:show] do
      get 'reserve', on: :collection
    end
  end

    

   root 'cite#index'

  

end

app/controllers/api/forms_controller.rb
module Api
  class FormsController < ApplicationController
    respond_to :json, :xml
    before_filter :default_format_xml

    def default_format_xml
      request.format = "xml" unless params[:format]
    end

    def show

    end

    def reserve(input)
      #params => id, type = (existing, newVers, newWork), user
      params = {}
      params = JSON.parse(input,:symbolize_names => true)
      received = params.permit()
      query = [] 
      #reserve version rows
      #have work and tg in tables
      if params[:type] == "existing"
        #copy pre-existing
        row = Version.where("version = #{ActiveRecord::Base.sanitize("#{params[:id]}")}")
          #need version urn and name of user
        #new edition entirely
      elsif params[:type] == "newVers"
          #need ed/trans?, language, perseus?, user name 
      
      #don't have work in tables
      elsif params[:type] == "newWork"
        
        #new edition entirely
          #need to reserve tg, work, and version rows
      end
      
      #change query to appropriate string, keeping here for the sanitize function 
      received.each {|k, v| query << "#{k} rlike #{ActiveRecord::Base.sanitize("#{v}")}"}

      #should return cts and cite urns
    end

    def mods(input)
      #params should be a hash of the mods csv plus any other useful fields (user, source of the request?)
      params = {}
      params = JSON.parse(input,:symbolize_names => true)
      @mods, v_arr, w_arr, tg_arr = Form.mods_creation(params)
      unless w_arr[1] == ""
        @new_w = Form.build_work_row(w_arr[1])
      end
      unless tg_arr[1] == ""
        @new_tg = Form.build_tg_row(tg_arr[1])
        @tg_cts = Form.mini_cts_tg(tg_arr[1])
      end
      @new_row = Form.build_row(v_arr[1])
      #save mods record to catalog_pending
      @path = Form.save_xml(@mods, v_arr[1])
      @v_cts = Form.mini_cts_work(v_arr[1])
    end
  end
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  respond_to :json, :html, :xml 
  #before_filter :authenticate
  def index
    
  end

  def show
  end

  def new
    @form = Form.new
  end

  def edit
  end

  def create
    re_arr = Form.arrayify(params[:arr])
    if params[:commit] == "Create Row"    
      @new_row = Form.build_row(re_arr)
    end
    if params[:commit] == "Create File"
      if params[:mods]
        unless params[:w_arr] == ""
          n_arr = Form.arrayify(params[:w_arr])
          @new_w = Form.build_work_row(n_arr)
        end

        unless params[:tg_arr] == ""
          tg_arr = Form.arrayify(params[:tg_arr])
          @new_tg = Form.build_tg_row(tg_arr)
          @tg_cts = Form.mini_cts_tg(tg_arr)
        end
        @new_row = Form.build_row(re_arr)
        #save mods record to catalog_pending
        @path = Form.save_xml(params[:mods], re_arr)
        @v_cts = Form.mini_cts_work(re_arr)
      elsif params[:mads]
        @new_a = Form.build_auth_row(re_arr)
        @path = Form.save_xml(params[:mads], re_arr)
      end 
    end
  end

  def search
    @s_res = Form.search(params)
  end

  def reserve
    if params[:obj]
      obj = params[:obj]
      if obj =~ /catwk/
        #new edition of work
        @w_row = Work.find_by_urn(obj)
      elsif obj =~ /catver/
        #reproducing an existing version
        @v_row = Version.find_by_urn(obj)
      else
        #something is wrong
      end
    elsif params[:commit] == "Reserve URN"
      #need to go back and add confirmation for values
      @v_arr = Form.build_vers_info(params)
    end
  end

  def mods
    if params[:obj]
      obj = params[:obj]
      if obj =~ /catwk/
        #new edition of work
        @w_row = Work.find_by_urn(obj)
      elsif obj =~ /catver/
        #reproducing an existing version
        @vers_row = Version.find_by_urn(obj)
        
      end
    elsif params["commit"] == "Create MODS"
      @mods, @v_arr, @w_arr, @tg_arr = Form.mods_creation(params)
    elsif params["commit"] == "Copy MODS"
      @mods, @v_arr, @w_arr, @tg_arr = Form.copy_mods(params)
    end
  end

  def mads
    if params[:commit] == "Create MADS"
      @mads, @a_arr = Form.mads_creation(params)
    end
  end
end

app/helpers/forms_helper.rb
module FormsHelper
  include CiteColls
  include ApplicationHelper


end

app/views/forms/_a_table.html.erb
<td><%= row.authority_name %></td>
<td><%= row.canonical_id %></td>
<td></td>
<td></td>
<td></td>

app/views/forms/_confirm.html.erb
<% if @v_arr %>

  <h5>Please review the information for your new version.</h5>
  <p>Note: Several of the fields appear blank or incomplete, do not worry, they will be filled in upon the completion of a MODS record.</p> 
  
  <%= render "row_display", num: 12, row: @v_arr %>

  <h5>If these values look correct, click the 'Create Row' button. If not, please consult the <%= link_to "CITE Tables", root_path  %> and begin again. Or contact us for help.</h5><br>

  <%= form_tag forms_create_path, :id => "create", :remote => "true" do %>
    <% arr_str = @v_arr[1].to_s %>
    <%= hidden_field_tag :arr, arr_str %>
    <%= submit_tag("Create Row", :id => "c_button") %>      
  <% end %>
  <%= button_to "Go Back", forms_path, method: "get", :id => "back"%>
<% end %>

app/views/forms/_mods.html.erb
<% unless @mods %> 
  <p>An * indicates a required field</p> 
  <% if @vers_row %>
    <%= render "vers_form", row: @vers_row %>
  <% else %>
    <%= form_tag forms_mods_path, :id => "mods_form", :remote => "true" do %>
      <div class = "field">
        <%= label_tag("Enter your name") %>
        <%= text_field_tag(:name, nil, :required => true) %>* 
      </div>
      <% if @w_row %>
        <% coll_id = @w_row.work %>
        <%= hidden_field_tag :w_cts, coll_id %>
        <% s_id = coll_id[/\w+\.\w+/] %>
        <% coll_title = @w_row.title_eng %>
        <% coll_auth = Textgroup.find_by_textgroup(coll_id[/urn:cts:\w+:\w+/]).groupname_eng %>
        <%= hidden_field_tag :tg_name, coll_auth %>
        <% coll_lang = @w_row.orig_lang %>
      <% else %>
        <div class = "field">
          <%= label_tag("What namespace does this edition belong to? ") %>
          <%= select_tag(:namespace, options_for_select([["greekLit", :greekLit], ["latinLit", :latinLit], ["arabicLit", :arabicLit]])) %> 
        </div>
        <div class = "field">
          <%= label_tag("If namespace did not appear above, enter it here") %>
          <%= text_field_tag(:o_namespace) %> 
        </div>
      <% end %>
      <div class = "field">
        <%= label_tag("Is this a Perseus edition? ") %>
        <%= select_tag(:perseus_check, options_for_select([["Yes", :perseus], ["No", :opp]]), :required => true) %>* 
      </div>
      <div class = "field">
        <%= label_tag("Primary ID") %>
        <%= text_field_tag(:p_id, s_id, :required => true, :size => "30") %>*
        <%= label_tag("ID type") %>
        <%= text_field_tag(:p_id_type, nil, :required => true) %>* 
      </div>
      <div class = "field">
        <%= label_tag("Alternate IDs (give in format 'id|type;...')") %>
        <%= text_field_tag(:alt_ids, nil, :size => "30") %>
      </div>
      <div class = "field">
        <%= label_tag("Primary Title") %>
        <%= text_field_tag(:title, coll_title, :required => true, :size => "30") %>* 
      </div>
      <%= button_tag("Add Alternate Titles", id: "add_button0", type: "button", onclick: "showMe('#add_fields0');")%>
      <div class = "hidden_field" id = "add_fields0" style = "display:none;">
        <%= label_tag("Alternate Titles (give in format 'title|type;...')") %>
        <%= text_field_tag(:alt_titles) %> 
      </div>

      <div class = "field">
        <%= label_tag("Author Name") %>
        <%= text_field_tag(:a_name, coll_auth, :required => true) %>* 
      </div>
      <div class = "field">
        <%= label_tag("Author Term of Address") %>
        <%= text_field_tag(:t_o_a) %> 
      </div>
      <div class = "field">
        <%= label_tag("Author Dates") %>
        <%= text_field_tag(:a_dates) %> 
      </div>
      <div class = "field">
        <%= label_tag("Author Authority") %>
        <%= text_field_tag(:a_auth) %> 
      </div>
      <div class = "field">
        <%= label_tag("Authority URL") %>
        <%= text_field_tag(:a_authURI) %> 
      </div>
      <div class = "field">
        <%= label_tag("Author Record at Authority") %>
        <%= text_field_tag(:a_valueURI) %> 
      </div>
      <!-- Person 1 -->
      <%= button_tag("Add an Editor or Translator", id: "add_button2", type: "button", onclick: "showMe('#person1');")%><br>
      <div class = "hidden_field" id="person1" style = "display:none;">
        <%= label_tag("Person role?") %>
        <%= select_tag(:ed_or_t1, options_for_select([["Editor", 'editor'], ["Translator", 'translator']])) %><br> 
        <%= label_tag("Name") %>
        <%= text_field_tag(:ed_or_t1_name) %><br> 
        <%= label_tag("Term of Address") %>
        <%= text_field_tag(:ed_or_t1_t_o_a) %><br> 
        <%= label_tag("Dates") %>
        <%= text_field_tag(:ed_or_t1_dates) %><br> 
        <%= label_tag("Person Authority") %>
        <%= text_field_tag(:ed_or_t1_auth) %><br> 
        <%= label_tag("Authority URL") %>
        <%= text_field_tag(:ed_or_t1_authURI) %><br> 
        <%= label_tag("Author Record at Authority") %>
        <%= text_field_tag(:ed_or_t1_valueURI) %><br> 
      </div>
      <!-- Person 2 -->
      <%= button_tag("Add an Editor or Translator", id: "add_button3", type: "button", onclick: "showMe('#person2');")%><br>
      <div class = "hidden_field" id="person2" style = "display:none;">
        <%= label_tag("Person role?") %>
        <%= select_tag(:ed_or_t2, options_for_select([["Editor", 'editor'], ["Translator", 'translator']])) %><br>
        <%= label_tag("Name") %>
        <%= text_field_tag(:ed_or_t2_name) %><br> 
        <%= label_tag("Term of Address") %>
        <%= text_field_tag(:ed_or_t2_t_o_a) %><br> 
        <%= label_tag("Dates") %>
        <%= text_field_tag(:ed_or_t2_dates) %><br> 
        <%= label_tag("Person Authority") %>
        <%= text_field_tag(:ed_or_t2_auth) %><br> 
        <%= label_tag("Authority URL") %>
        <%= text_field_tag(:ed_or_t2_authURI) %><br> 
        <%= label_tag("Author Record at Authority") %>
        <%= text_field_tag(:ed_or_t2_valueURI) %><br> 
      </div>
      <!-- Person 3 -->
      <%= button_tag("Add an Editor or Translator", id: "add_button4", type: "button", onclick: "showMe('#person3');")%><br>
      <div class = "hidden_field" id="person3" style = "display:none;">
        <%= label_tag("Person role?") %>
        <%= select_tag(:ed_or_t3, options_for_select([["Editor", 'editor'], ["Translator", 'translator']]), :required => true) %><br>
        <%= label_tag("Name") %>
        <%= text_field_tag(:ed_or_t3_name) %><br>
        <%= label_tag("Term of Address") %>
        <%= text_field_tag(:ed_or_t3_t_o_a) %><br>
        <%= label_tag("Dates") %>
        <%= text_field_tag(:ed_or_t3_dates) %><br>
        <%= label_tag("Person Authority") %>
        <%= text_field_tag(:ed_or_t3_auth) %><br>
        <%= label_tag("Authority URL") %>
        <%= text_field_tag(:ed_or_t3_authURI) %><br>
        <%= label_tag("Author Record at Authority") %>
        <%= text_field_tag(:ed_or_t3_valueURI) %><br> 
      </div>
      <div>**If you have additional authors/editors/translators to add to the record, include their names in a note below.**</div>
      <div class= "field">
        <%= label_tag("Manuscript?") %>
        <%= select_tag :ms?, options_for_select([["Yes", :true], ["No", :false]]) %> 
      </div>
      <div class= "field">
        <%= label_tag("Publisher Country") %>
        <%= text_field_tag(:c_code) %>
        <%= link_to "Country code list", "http://www.loc.gov/marc/countries/countries_name.html" %> 
      </div>
      <div class= "field">
        <%= label_tag("Publisher City") %>
        <%= text_field_tag(:city) %> 
      </div>
      <div class= "field">
        <%= label_tag("Publisher") %>
        <%= text_field_tag(:pub) %> 
      </div>
      <div class= "field">
        <%= label_tag("Date Issued") %>
        <%= text_field_tag(:date_i) %> 
      </div>
      <div class= "field">
        <%= label_tag("Date Created") %>
        <%= text_field_tag(:date_c) %> 
      </div>
      <div class= "field">
        <%= label_tag("Date Modified") %>
        <%= text_field_tag(:date_m) %> 
      </div>
      <div class= "field">
        <%= label_tag("Edition") %>
        <%= text_field_tag(:edition) %> 
      </div>
      <div class= "field">
        <%= label_tag("Work Original Language") %>
        <%= text_field_tag(:w_lang, coll_lang, :required => true) %>*
        <%= link_to "Language code list", "http://www.loc.gov/marc/languages/language_name.html" %> 
      </div>
      <div class= "field">
        <%= label_tag("Version Text Language") %>
        <%= text_field_tag(:lang_code, nil, :required => true) %>* 
      </div>
      <div class= "field">
        <%= label_tag("Other Languages (give in format 'language code|object part;...')") %>
        <%= text_field_tag(:other_langs) %> 
      </div>
      <div class= "field">
        <%= label_tag("Extent Description") %>
        <%= text_field_tag(:extent_desc) %> 
      </div>
      <div>If your work takes up only part of a volume, give the extent either as a start and end pair or a range (2-5). Range can also take a list of values (2-5, 7-9). If expressing extent in something other than pages, provide the unit after a ; in the start or range fields, e.g. 4v;folio.</div>
      <div class= "field">
        <%= label_tag("Page Start") %>
        <%= text_field_tag(:pg_s) %>
        <%= label_tag("Page End") %>
        <%= text_field_tag(:pg_e) %>
      </div>
      <div class= "field">
        <%= label_tag("Page Range") %>
        <%= text_field_tag(:pg_range) %> 
      </div>  
      <div class= "field">
        <%= label_tag("Topics (give as ; separated list)") %>
        <%= text_field_tag(:topics) %> 
      </div>  
      <div class= "field">
        <%= label_tag("Series") %>
        <%= text_field_tag(:series_title) %> 
      </div>  
      <div class= "field">
        <%= label_tag("Online Locations (give as 'label|url;...')") %>
        <%= text_field_tag(:online_loc) %> 
      </div> 
      <div class= "field">
        <%= label_tag("Physical Locations (give as 'type|name;...')") %>
        <%= text_field_tag(:phys_loc) %> 
      </div>  
      <div class= "field">
        <%= label_tag("Shelf Location") %>
        <%= text_field_tag(:shelf_loc) %> 
      </div>  
      <div class= "field">
        <%= label_tag("Notes") %>
        <%= text_area_tag(:notes) %> 
      </div>  
      <div class= "field">
        <%= label_tag("Table of Contents") %>
        <%= text_area_tag(:t_o_c) %> 
      </div>  
      <div class= "field">
        <%= label_tag("Is this a Multivolume Work?") %>
        <%= select_tag :multi?, options_for_select([["No", :false], ["Yes", :true]]) %> 
      </div>  
      <%= submit_tag("Create MODS", :id => "mods_button") %>
    <% end %>
  <% end %>
<% else %>
  <h5>Please double check the generated XML file and the new CITE rows</h5>
  <% doc = Nokogiri::XML(@mods) %>
  <div class="xml_block">
    <pre><%= doc.to_xml %></pre>
  </div>
  <div> Version Row
    <%= render "row_display", num: 11, row: @v_arr %>
  </div>
  <% if @w_arr != []%>
    <div> Work Row    
      <%= render "row_display", num: 9, row: @w_arr %>     
    </div>
  <% end %>
  <% if @tg_arr != []%>
    <div> Textgroup Row
      <%= render "row_display", num: 10, row: @tg_arr %>    
    </div>
  <% end %>
  <h5>If these values look correct, click the 'Create File' button. If not, please consult the <%= link_to "CITE Tables", root_path  %> and begin again. Or contact us for help.</h5> 
  <% w_str = @w_arr != [] ? @w_arr[1].to_s : "" %>
  <% tg_str = @tg_arr != [] ? @tg_arr[1].to_s : "" %>
  <%= form_tag forms_create_path, :id => "mods_create", :remote => "true" do %>
    <%= hidden_field_tag :mods, @mods %>
    <% arr_str = @v_arr[1].to_s %>
    <%= hidden_field_tag :arr, arr_str %>
    <%= hidden_field_tag :w_arr, w_str %>
    <%= hidden_field_tag :tg_arr, tg_str %>
    <%= submit_tag("Create File", :id => "create_file") %>
  <% end %>
<% end %>

app/views/forms/_reserve.html.erb
<% if @w_row %>

  <table>
    <tr>
      <%= render "w_table", row: @w_row %>
    </tr>
  </table>
  <h5>Please enter the following information for your new edition of the work you selected.</h5><br>
  <div id="reserve_container">
    <%= form_tag forms_reserve_path, :id => "reserve_form", :remote => "true" do %>
      <%= label_tag("Enter the type of version") %>
      <%= text_field_tag(:v_type, nil, :placeholder => "edition or translation") %><br>
      <%= label_tag("Enter the language code for the version") %>
      <%= text_field_tag(:lang_code, nil, :placeholder => "lat, grc, eng, etc.") %><br>
      <%= label_tag("Is this a Perseus edition? ") %>
      <%= select_tag(:perseus_check, options_for_select([["Yes", :perseus], ["No", :opp]])) %><br>
      <%= label_tag("Enter your name") %>
      <%= text_field_tag(:name) %><br>
      <%= hidden_field_tag :w_cts, @w_row.work %>
      <%= hidden_field_tag :w_title, @w_row.title_eng %>
      <%= hidden_field_tag :w_lang, @w_row.orig_lang %>
      <%= submit_tag("Reserve URN", :id => "res_button") %>
    <% end %>
  </div>
<% elsif @v_row %>
  <table>
    <tr>
      <%= render "v_table", row: @v_row %>
    </tr>
  </table>
  <div id="v_reserve_container">
    <%= form_tag forms_reserve_path, :id => "v_reserve_form", :remote => "true" do %>
      <%= label_tag("Enter your name") %>
      <%= text_field_tag(:name) %>
      <%= hidden_field_tag :v_cts, @v_row.version %>
      <%= hidden_field_tag :v_label, @v_row.label_eng %>
      <%= hidden_field_tag :v_desc, @v_row.desc_eng %>
      <%= hidden_field_tag :v_type, @v_row.ver_type %>
      <%= submit_tag("Reserve URN", :id => "v_res_button") %>
    <% end %>
  </div>
<% end %>

app/views/forms/_row_display.html.erb
  <table>
    <% i = 0 %>
    <% until i == num do %>
      <tr>
        <td><%= row[0][i] %></td>
        <td><%= row[1][i] %></td>
      </tr>
      <% i += 1 %>
    <% end %>
  </table><br>

app/views/forms/_search.html.erb
<% if @s_res %>
  <% if @s_res == [] %>
    <h5>The work id that you provided is not in the database, please search by other criteria to find your desired work.</h5>
    <%= form_tag forms_search_path, :id => "alt_search", :remote => "true" do %>
      <%= label_tag("Author Name") %>
      <%= text_field_tag(:authority_name) %>
      <%= label_tag("Work Title") %>
      <%= text_field_tag(:title_eng) %>
      <%= submit_tag("Search", :id => "add_search") %>
    <% end %>
  <% elsif @s_res == "" %>
    <h5>Your provided work and/or author returned no results, if you are sure of the spelling and want to add a new record, please <%= link_to "click here", forms_mods_path, :remote => "true", :method => "post" %>, or <%= link_to "go back", forms_path %>.</h5>  
  <% else %>
    <h5>Find the correct work for your new edition below, and then please select if you would like to reserve a URN or create a full MODS record.</h5>
    <% if params[:authority_name] && params[:title_eng] %>
      <h5>If you still do not see the work you are looking for and have a work id, <%= link_to "add the work", forms_mods_path, :remote => "true", :method => "post" %>.</h5>
    <% end %>
    <div id="s_tbl">
      <table>
        <% @s_res.each do |row| %>        
        <tr>
          <% if row.class == Author %>
            <%= render "a_table", row: row %>
          <% elsif params[:field_type] == "work" || row.class == Work %>
            <%= render "w_table", row: row %>
            <td><%= form_tag forms_reserve_path, :id => "reserve", :remote => "true" do %>
                  <%= hidden_field_tag :obj, row.urn %>
                  <%= submit_tag("Reserve URN", :id => "r_button") %>      
                <% end %>
            </td>
            <td><%= form_tag forms_mods_path, :id => "mods", :remote => "true" do %>
                  <%= hidden_field_tag :obj, row.urn %>
                  <%= submit_tag("Create New MODS", :id => "m_button") %>      
                <% end %>
            </td>
          <% elsif params[:field_type] == "version" %>
            <%= render "v_table", row: row %>
          
            <td><%= form_tag forms_reserve_path, :id => "reserve", :remote => "true" do %>
                  <%= hidden_field_tag :obj, row.urn %>
                  <%= submit_tag("Reserve URN", :id => "r_button") %>      
                <% end %>
            </td>
            <td><%= form_tag forms_mods_path, :id => "mods", :remote => "true" do %>
                  <%= hidden_field_tag :obj, row.urn %>
                  <%= submit_tag("Create New MODS", :id => "m_button") %>      
                <% end %>
            </td>
          <% end %>
        </tr>
        <% end %>
      </table>
    </div>
  <% end %>
<% end %> 

app/views/forms/_success.html.erb
<h4>Success!</h4>
<h5>Your created URNs are:</h5>
<% if @new_row %>  
    <ul style="list-style-type:none">
      <li>Version URNs</li>
      <ul>
        <li>CITE URN <%= @new_row[0] %></li>
        <li>CTS URN <%= @new_row[1] %></li>
      </ul>
      <% if @new_w %>
        <li>Work URNs</li>
        <ul>
          <li>CITE URN <%= @new_w[0] %></li>
          <li>CTS URN <%= @new_w[1] %></li>
        </ul>
      <% end %>
      <% if @new_tg %>
        <li>Textgroup URNs</li>
        <ul>
          <li>CITE URN <%= @new_tg[0] %></li>
          <li>CTS URN <%= @new_tg[1] %></li>
        </ul>
      <% end %>
    </ul>
    <p>Please make note of these URNs and include your CTS URN with your new edition and its catalog record. Also, please note the CTS Text Inventory information provided below for your added edition.</p>
    <% if @tg_cts %>
      <% doc = Nokogiri::XML(@tg_cts) %>
      <div class="xml_block">
        <%= doc.to_xml %>
      </div>
    <% end %>

    <% if @v_cts %>
      <% doc = Nokogiri::XML(@v_cts) %>
      <div class="xml_block">
        <%= doc.to_xml %>
      </div>
    <% end %>
  
  <% if @path %>
    <h5>Your new MODS file is saved at:</h5>
    <p><%= @path %></p>

    <% if @new_row[1][/\w+\./] && Author.get_by_id(@new_row[1][/\w+\./].chop) == [] %>
      <h5>There does not appear to be an author on file for this id.
        Would you like to <%= link_to "create a MADS file", forms_mads_path, :remote => "true", :method => "post" %>?</h5>
      
    <% end %>
  <% end %>
<% elsif @new_a %>
  <ul style="list-style-type:none">
    <li>Author URNs</li>
    <ul>
      <li>CITE URN <%= @new_a[0] %></li>
      <li>Standard ID <%= @new_a[2] %></li>
    </ul>
  </ul>
  <% if @path %>
    <h5>Your new MADS file is saved at:</h5>
    <p><%= @path %></p>
  <% end %>
<% end %>

<%= button_to "Go Back", forms_path, :method => "get", :id => "back"%>

app/views/forms/_vers_form.html.erb
<%= form_tag forms_mods_path, :id => "mods_form", :remote => "true" do %>
  <%= hidden_field_tag :v_cts, row.version %>
  <%= hidden_field_tag :v_label, row.label_eng %>
  <%= hidden_field_tag :v_desc, row.desc_eng %>
  <%= hidden_field_tag :v_type, row.ver_type %>
  <%= label_tag("Enter your name") %>
  <%= text_field_tag(:name, nil, :required => true) %>*<br>
  <%= label_tag("Editor Name") %>
  <%= text_field_tag(:e_name, nil, :required => true) %>*<br>
  <%= label_tag("Date") %>
  <%= text_field_tag(:date, nil, :required => true) %>*<br>
  <%= label_tag("Edition") %>
  <%= text_field_tag(:edition, "Epidoc Edition", :required => true) %>*<br>
  <%= submit_tag("Copy MODS", :id => "mods_button") %>
<% end %>

app/views/forms/_w_table.html.erb
<td><%= row.work %></td>
<td><%= row.title_eng %></td>
<td><%= row.orig_lang %></td>

  

app/views/forms/create.js.erb
$('#thirdPart').html("<%= escape_javascript(render(:partial => 'success')) %>");

app/views/forms/index.html.erb
<h1>Reserve URNs or Create New Records</h1>

  <div id="firstPart">
    <%= form_tag forms_search_path, :id => "init_search", :remote => "true" do %>
      <%= label_tag("Is this a new version from an existing edition or translation?") %>
      <%= select_tag :field_type, options_for_select([["Yes", :version], ["No", :work]]) %><br>
      <%= label_tag("Enter the Work ID") %>
      <%= text_field_tag(:search, nil, :size => "30") %>
      <%= submit_tag("Search", :id => "s_button") %>
      
    <% end %>

    <div id="otherSearch">
      <p>Don't have a Work ID to search by?</p>
    </div>
  </div>
  <div id="secondPart">
   
  </div>

  <div id="thirdPart">
    
  </div>

app/views/forms/index.js.erb
$(document).ajaxSend(function(e, xhr, options) {
 var token = $("meta[name='csrf-token']").attr("content");
  xhr.setRequestHeader("X-CSRF-Token", token);
});

app/views/forms/mods.js.erb
$('#secondPart').html("<%= escape_javascript(render(:partial => 'mods')) %>");

app/views/forms/search.js.erb
$('#secondPart').html("<%= escape_javascript(render(:partial => 'search')) %>");