config/routes.rb
CiteCollections::Application.routes.draw do
  
  get "cite/index"
  resources :versions, :constraints => {:id => /urn:cite:\w+:\w+\.*\w*\.*\w*-*\w*/}, only: [:index, :show, :edit, :update] do
    collection do
      get 'search'
    end
  end

  resources :works, :constraints => {:id => /urn:cite:\w+:\w+\.*\w*\.*\w*-*\w*/}, only: [:index, :show, :edit, :update] do
    collection do
        get 'search'
      end
    end

  resources :textgroups, :constraints => {:id => /urn:cite:\w+:\w+\.*\w*\.*\w*-*\w*/}, only: [:index, :show, :edit, :update] do
    collection do
      get 'search'
    end
  end

  resources :authors, :constraints => {:id => /urn:cite:\w+:\w+\.*\w*\.*\w*-*\w*/}, only: [:index, :show, :edit, :update] do
    collection do
      get 'search'
    end
  end

  get 'forms' => 'forms#index'
  post 'forms/search' => 'forms#search'
  post 'forms/reserve' => 'forms#reserve'
  post 'forms/create' => 'forms#create'
  post 'forms/mods' => 'forms#mods'
  post 'forms/mads' => 'forms#mads'

  namespace :api do
    resources :authors, :works, :textgroups, :versions, :constraints => {:id => /urn:cite:\w+:\w+\.*\w*\.*\w*-*\w*/}, only: [:index, :show] do
      collection do
        get 'count'
        get 'first'
        get 'last'
        get 'search'
        get 'redirect'
      end
      member do
        get 'previous'
        get 'next'
        get 'prevnext'
      end
    end
    resources :forms, only: [:show] do
      get 'reserve', on: :collection
    end
  end

    

   root 'cite#index'

  

end

app/controllers/cite_controller.rb
class CiteController < ApplicationController
  
end

app/helpers/cite_helper.rb
module CiteHelper
end

app/views/cite/index.html.erb
  <h2> Select the CITE collection to view </h2>
  <ul>
    <li> <%= link_to "List of Authors", authors_path %> </li>
    <li> <%= link_to "List of Textgroups", textgroups_path %> </li>
    <li> <%= link_to "List of Works", works_path %> </li>
    <li> <%= link_to "List of Versions", versions_path %> </li>
  </ul>

  <br>

  <h2> Or search on a field </h2>
  <br>
  <h4> Authors search </h4>
  <%= form_tag search_authors_path, :method => 'get' do %>
    <p>
      <%= select_tag :field_type, options_for_select([['CITE URN', :urn], ['Author name', :authority_name], ['CTS URN', :canonical_id], ['File path', :mads_file], ['Alternate ids', :alt_ids], ['Related works', :related_works], ['Status', :urn_status], ['Redirect to', :redirect_to], ['Created by', :created_by], ['Edited by', :edited_by]])%>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
  <% end %>
  <br>
  <h4> Textgroups search </h4>
  <%= form_tag search_textgroups_path, :method => 'get' do %>
    <p>
      <%= select_tag :field_type, options_for_select([['CITE URN', :urn], ['CTS URN', :textgroup], ['Group name', :groupname_eng], ['Has MADS?', :has_mads], ['MADS possible?', :mads_possible], ['Notes', :notes], ['Status', :urn_status], ['Redirect to', :redirect_to], ['Created by', :created_by], ['Edited by', :edited_by]])%>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
  <% end %>
  <br>
  <h4> Works search </h4>
  <%= form_tag search_works_path, :method => 'get' do %>
    <p>
      <%= select_tag :field_type, options_for_select([['CITE URN', :urn], ['CTS URN', :work], ['Work title', :title_eng], ['Original language', :orig_lang], ['Notes', :notes], ['Status', :urn_status], ['Redirect to', :redirect_to], ['Created by', :created_by], ['Edited by', :edited_by]])%>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
  <% end %>
  <br>
  <h4> Version search </h4>
  <%= form_tag search_versions_path, :method => 'get' do %>
    <p>
      <%= select_tag :field_type, options_for_select([['CITE URN', :urn], ['CTS URN', :version], ['Label', :label_eng], ['Description', :desc_eng], ['Edition or Translation', :ver_type], ['Has MODS?', :has_mods], ['Status', :urn_status], ['Redirect to', :redirect_to], ['Member of', :member_of], ['Created by', :created_by], ['Edited by', :edited_by]])%>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
  <% end %>
  <br>
  <%= link_to "Reserve a URN or create a new Catalog record", forms_path %>