config/routes.rb
CiteCollections::Application.routes.draw do
  
  get "cite/index"
  resources :versions, :constraints => {:id => /urn:cite:\w+:\w+\.*\w*\.*\w*-*\w*/}, only: [:index, :show, :edit, :update] do
    collection do
      get 'search'
    end
  end

  resources :works, :constraints => {:id => /urn:cite:\w+:\w+\.*\w*\.*\w*-*\w*/}, only: [:index, :show, :edit, :update] do
    collection do
        get 'search'
      end
    end

  resources :textgroups, :constraints => {:id => /urn:cite:\w+:\w+\.*\w*\.*\w*-*\w*/}, only: [:index, :show, :edit, :update] do
    collection do
      get 'search'
    end
  end

  resources :authors, :constraints => {:id => /urn:cite:\w+:\w+\.*\w*\.*\w*-*\w*/}, only: [:index, :show, :edit, :update] do
    collection do
      get 'search'
    end
  end

  get 'forms' => 'forms#index'
  post 'forms/search' => 'forms#search'
  post 'forms/reserve' => 'forms#reserve'
  post 'forms/create' => 'forms#create'
  post 'forms/mods' => 'forms#mods'
  post 'forms/mads' => 'forms#mads'

  namespace :api do
    resources :authors, :works, :textgroups, :versions, :constraints => {:id => /urn:cite:\w+:\w+\.*\w*\.*\w*-*\w*/}, only: [:index, :show] do
      collection do
        get 'count'
        get 'first'
        get 'last'
        get 'search'
        get 'redirect'
      end
      member do
        get 'previous'
        get 'next'
        get 'prevnext'
      end
    end
    resources :forms, only: [:show] do
      get 'reserve', on: :collection
    end
  end

    

   root 'cite#index'

  

end

app/models/textgroup.rb
class Textgroup < ActiveRecord::Base
  has_many :works
  has_many :authors
  
  def self.latest_urn
    latest_urn = Textgroup.last['urn']
  end

  def self.generate_urn
    last_urn = Textgroup.latest_urn
    unless last_urn
      new_urn = "urn:cite:perseus:cattg.1.1"
    else
      urn_parts = last_urn.split('.')
      inc_urn = urn_parts[1].to_i + 1
      new_urn = "urn:cite:perseus:cattg.#{inc_urn}.1"
    end
  end

  def self.find_by_id(id)
    found_id = Textgroup.find_by_textgroup(id)
  end

  def self.update_row(info_hash, editor)
    tg = info_hash[:cite_tg]
    tg_hash = {}
    if tg.groupname_eng != info_hash[:a_name]
      tg_hash[:groupname_eng] = info_hash[:a_name]
      tg_hash[:edited_by] = editor
      Textgroup.update(tg.id, tg_hash)
    end
  end
  
  def self.add_cite_row(v)
    #0urn, 1textgroup, 2groupname_eng, 3has_mads, 4mads_possible, 5notes, 
    #6urn_status, 7redirect_to, 8created_by, 9edited_by
    tg = Textgroup.new do |t|
      t.urn = v[0]
      t.textgroup = v[1]
      t.groupname_eng = v[2]
      t.has_mads = v[3] 
      t.mads_possible = v[4] 
      t.notes = v[5]
      t.urn_status = v[6]
      t.redirect_to = v[7] 
      t.created_by = v[8]
      t.edited_by = v[9]
    end
    tg.save
  end

  def self.lookup(params)
    type = params[:field_type]
    search = params[:search]
    valid_cols = ['urn', 'textgroup', 'groupname_eng', 'has_mads', 'mads_possible', 'notes', 'urn_status', 'redirect_to', 'created_by', 'edited_by']
    if valid_cols.include?(type)
      result = Textgroup.all(:conditions => ["#{type} rlike ?", search])
    else
      result = nil
    end
  end

  def prev
    unless self.id == 1
      prev = Textgroup.find(self.id - 1)
    else
      prev = nil
    end
    return prev
  end

  def next
    unless self.id == Textgroup.last.id
      nxt = Textgroup.find(self.id + 1)
    else
      nxt = nil
    end
    return nxt
  end

  def prevnext
    prev = self.prev
    nxt = self.next
    return prev, nxt
  end
end

app/controllers/api/textgroups_controller.rb
module Api
  class TextgroupsController < ApplicationController
    respond_to :json, :xml
    before_action :set_textgroup, only: [:show, :previous, :next, :prevnext]
    before_filter :default_format_xml

    def default_format_xml
      request.format = "xml" unless params[:format]
    end
    
    def index
      @textgroups = Textgroup.all
      respond_with(@textgroups, except: :id)
    end

    def show
      respond_with(@textgroup, except: :id)
    end

    def count     
      c = Textgroup.count
      @count = {:collection_size => c}
      respond_with(@count)
    end

    def first
      @first = Textgroup.first
      respond_with(@first, except: :id)
    end

    def last
      @last = Textgroup.last
      respond_with(@last, except: :id)
    end

    def previous
      @prev = @textgroup.prev
      respond_with(@prev, except: :id)
    end

    def next
      @next = @textgroup.next
      respond_with(@next, except: :id)
    end

    def prevnext
      @prev, @next = @textgroup.prevnext
      @both = {:previous => @prev, :next => @next}
      respond_with(@both, except: :id)
    end

    def search
      received = params.permit(:urn, :textgroup, :groupname_eng, :has_mads, :mads_possible, :notes, :urn_status, :redirect_to, :created_by, :edited_by)
      query = []
      received.each  {|k, v| query << "#{k} rlike #{ActiveRecord::Base.sanitize("#{v}")}"}
      @response = Textgroup.where(query.join(" AND "))
      respond_with(@response, except: :id)
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_textgroup
          @textgroup = Textgroup.find_by_urn(params[:id])
      end
    end
end

app/controllers/textgroups_controller.rb
class TextgroupsController < ApplicationController
  before_filter :authenticate, except: [:show, :index, :search]
  before_action :set_textgroup, only: [:show, :edit, :update, :destroy]

  # GET /textgroups
  # GET /textgroups.json
  def index
    session[:search_results] = request.url
    @textgroups = Textgroup.where(urn_status: "published").load
  end

  # GET /textgroups/1
  # GET /textgroups/1.json
  def show
  end

  # GET /textgroups/new
  def new
    @textgroup = Textgroup.new
  end

  # GET /textgroups/1/edit
  def edit
  end

  # POST /textgroups
  # POST /textgroups.json
  def create
    @textgroup = Textgroup.new(textgroup_params)

    respond_to do |format|
      if @textgroup.save
        format.html { redirect_to textgroup_path(@textgroup.urn), notice: 'Textgroup was successfully created.' }
        format.json { render action: 'show', status: :created, location: @textgroup }
      else
        format.html { render action: 'new' }
        format.json { render json: @textgroup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /textgroups/1
  # PATCH/PUT /textgroups/1.json
  def update
    respond_to do |format|
      if @textgroup.update(textgroup_params)
        format.html { redirect_to @textgroup, notice: 'Textgroup was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @textgroup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /textgroups/1
  # DELETE /textgroups/1.json
  def destroy
    @textgroup.destroy
    respond_to do |format|
      format.html { redirect_to textgroups_url }
      format.json { head :no_content }
    end
  end

  def search
    session[:search_results] = request.url
    @textgroups = Textgroup.lookup(params)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_textgroup
      @textgroup = Textgroup.find_by_urn(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def textgroup_params
      params.require(:textgroup).permit(:urn, :textgroup, :groupname_eng, :has_mads, :mads_possible, :notes, :urn_status, :redirect_to, :created_by, :edited_by)
    end
end

app/helpers/textgroups_helper.rb
module TextgroupsHelper
end

app/views/textgroups/_form.html.erb
<%= form_for @textgroup, :url => textgroup_path do |f| %>
  <% if @textgroup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@textgroup.errors.count, "error") %> prohibited this textgroup from being saved:</h2>

      <ul>
      <% @textgroup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :urn %><br>
    <%= f.text_field :urn %>
  </div>
  <div class="field">
    <%= f.label :textgroup %><br>
    <%= f.text_field :textgroup %>
  </div>
  <div class="field">
    <%= f.label :groupname_eng %><br>
    <%= f.text_field :groupname_eng %>
  </div>
  <div class="field">
    <%= f.label :has_mads %><br>
    <%= f.text_field :has_mads %>
  </div>
  <div class="field">
    <%= f.label :mads_possible %><br>
    <%= f.text_field :mads_possible %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :urn_status %><br>
    <%= f.text_field :urn_status %>
  </div>
  <div class="field">
    <%= f.label :redirect_to %><br>
    <%= f.text_field :redirect_to %>
  </div>
  <div class="field">
    <%= f.label :created_by %><br>
    <%= f.text_field :created_by %>
  </div>
  <div class="field">
    <%= f.label :edited_by %><br>
    <%= f.text_field :edited_by %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/textgroups/edit.html.erb
<h1>Editing textgroup</h1>

<%= render 'form' %>

<%= link_to 'Show', @textgroup.urn %> |
<%= link_to 'Back', request.referer %>

app/views/textgroups/index.html.erb
<h1>Listing textgroups</h1>

<br>
<%= link_to "Return to main page", root_path %>
<br>
<div class="index_table">
  <table>
    <thead>
      <tr>
        <th>Urn</th>
        <th>Textgroup</th>
        <th>Groupname eng</th>
        <th>Has mads</th>
        <th>Mads possible</th>
        <th>Notes</th>
        <th>Urn status</th>
        <th>Redirect to</th>
        <th>Created by</th>
        <th>Edited by</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @textgroups.each do |textgroup| %>
        <tr>
          <td><%= textgroup.urn %></td>
          <td><%= textgroup.textgroup %></td>
          <td><%= textgroup.groupname_eng %></td>
          <td><%= textgroup.has_mads %></td>
          <td><%= textgroup.mads_possible %></td>
          <td><%= textgroup.notes %></td>
          <td><%= textgroup.urn_status %></td>
          <td><%= textgroup.redirect_to %></td>
          <td><%= textgroup.created_by %></td>
          <td><%= textgroup.edited_by %></td>
          <td><%= link_to 'Show', textgroup_path(textgroup.urn) %></td>
          <td><%= link_to 'Edit', edit_textgroup_path(textgroup.urn) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/textgroups/new.html.erb
<h1>New textgroup</h1>

<%= render 'form' %>

<%= link_to 'Back', textgroups_path %>

app/views/textgroups/search.html.erb
<% unless @textgroups == nil || @textgroups.empty? %>
  <h1>Search Results</h1>

  <table>
    <thead>
      <tr>
        <th>Urn</th>
        <th>Textgroup</th>
        <th>Groupname eng</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @textgroups.each do |textgroup| %>
        <tr>
          <td><%= textgroup.urn %></td>
          <td><%= textgroup.textgroup %></td>
          <td><%= textgroup.groupname_eng %></td>
          <td><%= link_to 'Show', textgroup_path(textgroup.urn) %></td>
          <td><%= link_to 'Edit', edit_textgroup_path(textgroup.urn) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h1>No results</h1>
  
<% end %>
<br>
<%= link_to "Return to main page", root_path %>

app/views/textgroups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Urn:</strong>
  <%= @textgroup.urn %>
</p>

<p>
  <strong>Textgroup:</strong>
  <%= @textgroup.textgroup %>
</p>

<p>
  <strong>Groupname eng:</strong>
  <%= @textgroup.groupname_eng %>
</p>

<p>
  <strong>Has mads:</strong>
  <%= @textgroup.has_mads %>
</p>

<p>
  <strong>Mads possible:</strong>
  <%= @textgroup.mads_possible %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @textgroup.notes %>
</p>

<p>
  <strong>Urn status:</strong>
  <%= @textgroup.urn_status %>
</p>

<p>
  <strong>Redirect to:</strong>
  <%= @textgroup.redirect_to %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @textgroup.created_by %>
</p>

<p>
  <strong>Edited by:</strong>
  <%= @textgroup.edited_by %>
</p>

<%= link_to 'Edit', edit_textgroup_path(@textgroup.urn) %> |
<% if request.referer =~ /edit/%>
  <%= link_to 'Back', session[:search_results] %>
<% else %>
  <%= link_to 'Back', request.referer %>
<% end %> |
<%= link_to "Return to main page", root_path %>